### ISSUE TITLE
Possible to use without Cuckoo box?

### ISSUE THREAD

**Issue by JohannesTK** [seanthegeek/routetor#2]
Looks like a great project that could be used as well for vanilla Virtualbox guests!

I tried to use it with vanilla Virtualbox guest but didn't get it going. 

My config:

Guest has host-only interface, eth0 192.168.56.103.

Host vboxnet0 192.168.56.1.

In /etc/tor/torrc: 

TransListenAddress 192.168.56.1
TransPort 9040
DNSListenAddress 192.168.56.1
DNSPort 5353

Tor version 0.2.8.6 (git-b88847615faea7c8).
netstat: 
tcp        0      0 192.168.56.1:9040       0.0.0.0:\*               LISTEN      14088/tor       

Ran ./routetor & and ./torstart 192.168.56.1

Log: 

2016-08-19 11:24:19,099 routetor: v2.0.1 starting
2016-08-19 11:25:28,581 routetor: starting transparent proxy for 192.168.56.1

tcpdump -i vboxnet0 from host:

12:19:33.523823 IP 192.168.56.103 > google-public-dns-a.google.com: ICMP echo request, id 2565, seq 6, length 64
12:19:34.532019 IP 192.168.56.103 > google-public-dns-a.google.com: ICMP echo request, id 2565, seq 7, length 64

iptables:

root@titan:~/routetor# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination  
DROP       all  --  anywhere             anywhere             state INVALID
DROP       all  --  anywhere             anywhere             ctstate INVALID
root@titan:~/routetor# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination  
REDIRECT   tcp  --  192.168.56.1         anywhere             tcp dpt:!2042 flags:FIN,SYN,RST,ACK/SYN redir ports 9040
REDIRECT   udp  --  192.168.56.1         anywhere             udp dpt:domain redir ports 5353

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination 

Are there any other iptables rules that should be used for the guest?

**Comment by seanthegeek** [comment]
I have not tested this with virtualbox, but I think I know what's going wrong.

Try running ./torstart with the IP address of the individual VM, not the one for the vboxnet0 interface.
